Repository ENCODE-DCC/encoded, pull requests merged in 2018-09, with the labels that each got.

#2404 ENCD-4173 Add Paul to test user inserts
  src/encoded/tests/data/inserts/user.json
Labels: Pending Review

#2400 ENCD-4208 Add png addition to qc mime types
  src/encoded/schemas/changelogs/complexity_xcorr_quality_metric.md
  src/encoded/schemas/complexity_xcorr_quality_metric.json
  src/encoded/tests/data/inserts/complexity_xcorr_quality_metric.json
Labels: Ready to Merge

#2392 ENCD-4196 Reduce cloud init size
  cloud-config-cluster.yml
  cloud-config-elasticsearch.yml
  cloud-config-no-es.yml
  cloud-config.yml
Labels: Ready to Merge

#2418 ENCD-4206 calc prop rebased
  src/encoded/types/shared_calculated_properties.py
Labels: Pending QA
