Repository ENCODE-DCC/encoded, pull requests merged in 2018-03, with the labels that each got.

#2145 ENCD-3821 Show biosample characterization doc links
  src/encoded/static/components/antibody.js
  src/encoded/static/components/biosample.js
  src/encoded/static/components/doc.js
  src/encoded/types/biosample.py
Labels: Trav-testing, ready to merge

#2152 ENCD-3880 Add Alembic documentation
  docs/database.rst
Labels: in progress

#2154 ENCD-3841 Add collapsing sections on schema pages
  src/encoded/static/components/schema.js
  src/encoded/static/scss/encoded/modules/_schema.scss
  src/encoded/static/scss/style.scss
Labels: Pending JS Review

#2163 ENCD-3828 Update redacted alignments
  src/encoded/audit/experiment.py
  src/encoded/schemas/changelogs/file.md
  src/encoded/schemas/file.json
  src/encoded/tests/test_audit_experiment.py
Labels: Pending Data Review

#2150 ENCD-3854 Fix report description column sort error
  src/encoded/search.py
  src/encoded/static/components/report.js
  src/encoded/static/scss/encoded/modules/_tables.scss
Labels: in progress

#2164 ENCD-3848 Remove immortalize from cell line
  src/encoded/audit/ontology_data.py
  src/encoded/schemas/annotation.json
  src/encoded/schemas/antibody_characterization.json
  src/encoded/schemas/biosample.json
  src/encoded/schemas/changelogs/annotation.md
  src/encoded/schemas/changelogs/antibody_characterization.md
  src/encoded/schemas/changelogs/biosample.md
  src/encoded/schemas/changelogs/experiment.md
  src/encoded/schemas/experiment.json
  src/encoded/schemas/mixins.json
  src/encoded/static/components/__tests__/datacolor-test.js
  src/encoded/static/components/app.js
  src/encoded/static/components/testdata/biosample/k562-1.js
  src/encoded/static/components/testdata/characterization/antibody-367a6fdd0cef.js
  src/encoded/static/components/testdata/experiment.js
  src/encoded/tests/data/inserts/annotation.json
  src/encoded/tests/data/inserts/antibody_characterization.json
  src/encoded/tests/data/inserts/biosample.json
  src/encoded/tests/data/inserts/experiment.json
  src/encoded/tests/test_audit_antibody_characterization.py
  src/encoded/tests/test_audit_antibody_lot.py
  src/encoded/tests/test_audit_experiment.py
  src/encoded/tests/test_audit_replicate.py
  src/encoded/tests/test_schema_antibody_characterization.py
  src/encoded/tests/test_types_antibody_lot.py
  src/encoded/tests/test_types_experiment.py
  src/encoded/tests/test_upgrade_biosample.py
  src/encoded/tests/test_upgrade_characterization.py
  src/encoded/tests/test_upgrade_dataset.py
  src/encoded/types/biosample.py
  src/encoded/types/experiment.py
  src/encoded/upgrade/biosample.py
  src/encoded/upgrade/characterization.py
  src/encoded/upgrade/dataset.py
Labels: in progress

#2171 ENCD-3604 Update boost to include GM accessions
  src/encoded/schemas/genetic_modification.json
  src/encoded/search.py
Labels: ready to merge

#2170 ENCD-3899 Fix exp audit trigger on non-encode pipelines
  src/encoded/audit/experiment.py
Labels: ready to merge

#2168 ENCD-3840 Add link to linkFrom linkTo schema properties
  src/encoded/static/components/schema.js
  src/encoded/static/scss/encoded/modules/_schema.scss
Labels: ready to merge

#2166 ENCD-3894 Move NIH cert audit to experiment
  src/encoded/audit/biosample.py
  src/encoded/audit/experiment.py
  src/encoded/tests/test_audit_biosample.py
  src/encoded/tests/test_audit_experiment.py
Labels: ready to merge

#2169 Major indexer overhaul march 2018
  base.ini
  buildout.cfg
  development.ini
  docs/indexers.rst
  etc/encoded-apache.conf
  production.ini.in
  setup.py
  src/encoded/__init__.py
  src/encoded/commands/deploy.py
  src/encoded/peak_indexer.py
  src/encoded/region_indexer.py
  src/encoded/region_search.py
  src/encoded/schemas/human_donor.json
  src/encoded/search.py
  src/encoded/static/vis_defs/ANNO_vis_def.json
  src/encoded/static/vis_defs/ATAC_vis_def.json
  src/encoded/static/vis_defs/ChIP_vis_def.json
  src/encoded/static/vis_defs/DNASE_vis_def.json
  src/encoded/static/vis_defs/GGRChIP_vis_def.json
  src/encoded/static/vis_defs/HIST_vis_def.json
  src/encoded/tests/conftest.py
  src/encoded/tests/features/test_trackhubs.py
  src/encoded/tests/test_indexing.py
  src/encoded/types/file.py
  src/encoded/types/shared_calculated_properties.py
  src/encoded/vis_defines.py
  src/encoded/vis_indexer.py
  src/encoded/visualization.py
Labels: Trav-testing, ready to merge

#2162 ENCD-3891 Fix file test for duplicates in derived_from
  src/encoded/tests/data/inserts/file.json
Labels: Trav-testing, snovault

#2167 ENCD-3839 Remove schemas for the deleted objects
  src/encoded/audit/biosample.py
  src/encoded/audit/experiment.py
  src/encoded/audit/item.py
  src/encoded/loadxl.py
  src/encoded/schemas/antibody_approval.json
  src/encoded/schemas/changelogs/antibody_approval.md
  src/encoded/schemas/changelogs/construct.md
  src/encoded/schemas/changelogs/crispr.md
  src/encoded/schemas/changelogs/fastqc_quality_metric.md
  src/encoded/schemas/changelogs/modification_technique.md
  src/encoded/schemas/changelogs/rnai.md
  src/encoded/schemas/changelogs/tale.md
  src/encoded/schemas/changelogs/talen.md
  src/encoded/schemas/construct.json
  src/encoded/schemas/crispr.json
  src/encoded/schemas/fastqc_quality_metric.json
  src/encoded/schemas/mixins.json
  src/encoded/schemas/modification_technique.json
  src/encoded/schemas/rnai.json
  src/encoded/schemas/tale.json
  src/encoded/schemas/talen.json
  src/encoded/static/components/__tests__/antibody-test.js
  src/encoded/static/components/biosample.js
  src/encoded/static/components/filegallery.js
  src/encoded/static/components/globals.js
  src/encoded/static/components/index.js
  src/encoded/static/components/talen.js
  src/encoded/static/components/testdata/lot_review/EFO-0002791.js
  src/encoded/static/components/typeutils.js
  src/encoded/tests/data/inserts/antibody_approval.json
  src/encoded/tests/data/inserts/construct.json
  src/encoded/tests/data/inserts/crispr.json
  src/encoded/tests/data/inserts/fastqc_quality_metric.json
  src/encoded/tests/data/inserts/rnai.json
  src/encoded/tests/data/inserts/tale.json
  src/encoded/tests/data/inserts/talen.json
  src/encoded/tests/datafixtures.py
  src/encoded/tests/test_upgrade_antibody_lot.py
  src/encoded/tests/test_upgrade_biosample.py
  src/encoded/tests/test_upgrade_construct.py
  src/encoded/tests/test_upgrade_donor.py
  src/encoded/tests/test_upgrade_rnai.py
  src/encoded/tests/test_views.py
  src/encoded/types/__init__.py
  src/encoded/types/antibody_approval.py
  src/encoded/types/base.py
  src/encoded/types/biosample.py
  src/encoded/types/modification_technique.py
  src/encoded/types/quality_metric.py
  src/encoded/upgrade/antibody_approval.py
  src/encoded/upgrade/antibody_lot.py
  src/encoded/upgrade/construct.py
  src/encoded/upgrade/fastqc_quality_metric.py
  src/encoded/upgrade/item.py
  src/encoded/upgrade/rnai.py
Labels: Pending Data Review, ready to merge

#2179 ENCD-3916 Fix for broken metadata queries
  src/encoded/batch_download.py
Labels: MASTER

#2192 ENCD-3780-remove-ready-for-review
  src/encoded/audit/experiment.py
  src/encoded/audit/item.py
  src/encoded/schemas/changelogs/experiment.md
  src/encoded/schemas/changelogs/reference.md
  src/encoded/schemas/changelogs/treatment_time_series.md
  src/encoded/schemas/dataset.json
  src/encoded/schemas/experiment.json
  src/encoded/schemas/reference.json
  src/encoded/schemas/treatment_time_series.json
  src/encoded/static/components/item.js
  src/encoded/tests/test_audit_experiment.py
  src/encoded/tests/test_permissions.py
  src/encoded/tests/test_schema_experiment.py
  src/encoded/tests/test_types_series.py
  src/encoded/tests/test_upgrade_dataset.py
  src/encoded/upgrade/dataset.py
Labels: Pending Data Review

#2178 ENCD-3189 Traverse root using external_accession key from files
  src/encoded/root.py
  src/encoded/tests/test_file.py
  src/encoded/types/file.py
Labels: Pending Code Review

#2190 ENCD-3938 Adding new Series type "AggregateSeries"
  src/encoded/loadxl.py
  src/encoded/schemas/aggregate_series.json
  src/encoded/schemas/changelogs/aggregate_series.md
  src/encoded/static/components/dataset.js
  src/encoded/static/components/search.js
  src/encoded/tests/data/inserts/aggregate_series.json
  src/encoded/types/dataset.py
Labels: Pending Data Review, Pending JS Review

#2176 ENCD [3823, 3864, 3868] - filter restricted files, batch_download refactor, add unit tests
  src/encoded/batch_download.py
  src/encoded/tests/test_batch_download.py
Labels: Pending Code Review, in progress

#2136 ENCD-3863 Eliminate repeated values in report TSV
  src/encoded/batch_download.py
Labels: ready to merge

#2181 ENCD-3886 Update deploy machine instance types
  checkfiles/deploy.py
  src/encoded/commands/deploy.py
Labels: ready to merge

#2187 ENCD-3898 adding an audit flagging "tagging" GM without characterization
  src/encoded/audit/genetic_modification.py
  src/encoded/tests/test_audit_genetic_modification.py
  src/encoded/types/experiment.py
Labels: ready to merge

#2193 ENCD-3935 adding new biosample type "single cell"
  src/encoded/schemas/biosample.json
  src/encoded/schemas/changelogs/annotation.md
  src/encoded/schemas/changelogs/antibody_lot.md
  src/encoded/schemas/changelogs/biosample.md
  src/encoded/schemas/changelogs/experiment.md
  src/encoded/schemas/experiment.json
  src/encoded/schemas/mixins.json
  src/encoded/static/components/app.js
  src/encoded/tests/data/inserts/biosample.json
  src/encoded/tests/test_types_biosample.py
  src/encoded/types/biosample.py
Labels: ready to merge

#2205 ENCD-3960 Fix batch download lookup column test
  src/encoded/tests/test_batch_download.py
Labels: ready to merge

#2206 ENCD-2992-clean-status-table
  src/encoded/types/base.py
Labels: ready to merge

#2188 ENCD-3739 rewriting chip control read depth audit
  src/encoded/audit/experiment.py
  src/encoded/tests/test_audit_experiment.py
  src/encoded/tests/test_audit_file.py
Labels: Pending Demo Test

#2201 ENCD-3944 Add organ slim shims & update ontology.json
  buildout.cfg
  npm-shrinkwrap.json
  src/encoded/commands/generate_ontology.py
  src/encoded/docs/updating_ontologies.md
Labels: ready to merge
