Repository ENCODE-DCC/encoded, pull requests merged in 2018-10, with the labels that each got.

#2398 ENCD-4202 fixing missing control audit
  src/encoded/audit/experiment.py
  src/encoded/tests/test_audit_experiment.py
Labels: Ready to Merge

#2393 ENCD-4171 Reset default audit inherit
  src/encoded/types/pipeline.py
Labels: Needs Snovault Update, Pending QA

#2433 ENCD-4254 Raise file validation error audit level in exp
  src/encoded/audit/experiment.py
Labels: Ready to Merge

#2434 ENCD-4176 fix BDSC links
  src/encoded/static/components/__tests__/dbxref-test.js
  src/encoded/static/components/dbxref.js
Labels: Ready to Merge

#2436 ENCD-4220 remove references to release ready status
  src/encoded/types/dataset.py
Labels: Pending QA

#2439 ENCD-4257-make-copying-matrix-data-a-deep-copy
  src/encoded/viewconfigs/auditview.py
Labels: Pending QA

#2425 ENCD-4185-s3-public-url
  src/encoded/tests/test_types_file.py
  src/encoded/types/file.py
Labels: Pending QA

#2428 ENCD-3701 Update events from search page text box
  src/encoded/static/components/search.js
Labels: Pending QA

#2445 ENCD-4229 Fix no story news news crash
  src/encoded/static/components/news.js
Labels: Pending Code Review

#2416 ENCD-3998 Link target gene
  src/encoded/schemas/aggregate_series.json
  src/encoded/schemas/annotation.json
  src/encoded/schemas/antibody_lot.json
  src/encoded/schemas/biosample.json
  src/encoded/schemas/changelogs/target.md
  src/encoded/schemas/experiment.json
  src/encoded/schemas/fly_donor.json
  src/encoded/schemas/genetic_modification.json
  src/encoded/schemas/matched_set.json
  src/encoded/schemas/mouse_donor.json
  src/encoded/schemas/organism_development_series.json
  src/encoded/schemas/project.json
  src/encoded/schemas/reference_epigenome.json
  src/encoded/schemas/replication_timing_series.json
  src/encoded/schemas/target.json
  src/encoded/schemas/treatment_concentration_series.json
  src/encoded/schemas/treatment_time_series.json
  src/encoded/schemas/ucsc_browser_composite.json
  src/encoded/schemas/worm_donor.json
  src/encoded/static/components/__tests__/dbxref-test.js
  src/encoded/static/components/antibody.js
  src/encoded/static/components/dbxref.js
  src/encoded/static/components/gene.js
  src/encoded/static/components/target.js
  src/encoded/static/components/testdata/lot_review.js
  src/encoded/static/components/testdata/target/HNRNPA1-human.js
  src/encoded/tests/data/inserts/gene.json
  src/encoded/tests/data/inserts/target.json
  src/encoded/tests/datafixtures.py
  src/encoded/tests/features/targets.feature
  src/encoded/tests/test_audit_antibody_characterization.py
  src/encoded/tests/test_audit_antibody_lot.py
  src/encoded/tests/test_audit_experiment.py
  src/encoded/tests/test_audit_reference_epigenome.py
  src/encoded/tests/test_schema_target.py
  src/encoded/tests/test_types_antibody_lot.py
  src/encoded/tests/test_upgrade_target.py
  src/encoded/types/antibody_lot.py
  src/encoded/types/biosample.py
  src/encoded/types/dataset.py
  src/encoded/types/donor.py
  src/encoded/types/experiment.py
  src/encoded/types/gene.py
  src/encoded/types/genetic_modification.py
  src/encoded/types/target.py
  src/encoded/upgrade/target.py
Labels: Pending QA

#2466 [3rd] ENCD-3998 upgrade return gene uuid
  src/encoded/tests/test_upgrade_target.py
  src/encoded/upgrade/target.py
Labels: Ready to Merge
