Repository ENCODE-DCC/encoded, pull requests merged in 2018-04, with the labels that each got.

#2213 [2ND] ENCD-3935 Remove duplicated code in dependency of experiment schema
  src/encoded/schemas/experiment.json
Labels: v68

#2215 Update to version 68.0
  CHANGES.rst
  setup.py
Labels: in progress

#2217 Release v68.0
  CHANGES.rst
  setup.py
  src/encoded/schemas/experiment.json
Labels: in progress

#2221 ENCD-3979 Fix zc buildout for pypi update
  .travis.yml
  README.md
  bootstrap.py
  buildout.cfg
  cloud-config-cluster.yml
  cloud-config.yml
  ez_setup.py
Labels: in progress

#2219 ENCD-3973 Redo how GM characterization documents get displayed
  src/encoded/static/components/biosample.js
  src/encoded/static/components/donor.js
  src/encoded/static/components/genetic_modification.js
Labels: in progress

#2223 ENCD-3726 adding platform to library
  src/encoded/schemas/biosample.json
  src/encoded/schemas/changelogs/biosample.md
  src/encoded/schemas/changelogs/library.md
  src/encoded/schemas/library.json
  src/encoded/tests/data/inserts/library.json
  src/encoded/tests/test_schema_biosample.py
Labels: in progress

#2225 ENCD-3216 Hide antibody characterizations via user access level
  src/encoded/static/components/__tests__/status-test.js
  src/encoded/static/components/antibody.js
  src/encoded/static/components/statuslabel.js
Labels: in progress

#2229 ENCD-3986 Update to snovault 1.0.7
  buildout.cfg
Labels: in progress

#2210 REG-9 Fix vis button for region search
  src/encoded/region_search.py
  src/encoded/static/components/region_search.js
Labels: Pending QA

#2230 Update to version 69.0
  CHANGES.rst
  setup.py
Labels: in progress

#2232 Revert "Update to version 69.0"
  CHANGES.rst
  setup.py
Labels: in progress

#2231 [2nd] ENCD-3980 Fix base ini ontology path
  ini-templates/base-template.ini
Labels: in progress

#2235 [2nd] ENCD-3896 Update snovault to 1.0.7a
  buildout.cfg
Labels: in progress
