Repository ENCODE-DCC/encoded, pull requests merged in 2018-05, with the labels that each got.

#2237 ENCD-3641 fix navigate to file download URI
  src/encoded/static/components/app.js
Labels: in progress

#2234 ENCD-3974 organoid
  src/encoded/schemas/annotation.json
  src/encoded/schemas/antibody_characterization.json
  src/encoded/schemas/biosample.json
  src/encoded/schemas/changelogs/annotation.md
  src/encoded/schemas/changelogs/antibody_characterization.md
  src/encoded/schemas/changelogs/biosample.md
  src/encoded/schemas/changelogs/experiment.md
  src/encoded/schemas/experiment.json
  src/encoded/schemas/mixins.json
  src/encoded/static/components/globals.js
  src/encoded/tests/test_schema_biosample.py
  src/encoded/upgrade/biosample.py
  src/encoded/upgrade/characterization.py
  src/encoded/upgrade/dataset.py
Labels: Pending QA

#2233 ENCD-3963 Remove antibody accession column
  src/encoded/batch_download.py
Labels: ready to merge

#2243 ENCD-4016 adding community to users
  src/encoded/schemas/changelogs/user.md
  src/encoded/schemas/user.json
  src/encoded/tests/test_upgrade_user.py
  src/encoded/upgrade/user.py
Labels: Pending QA

#2239 ENCD-3995 Update file output_type
  src/encoded/schemas/file.json
Labels: Pending QA

#2238 ENCD-4010 fixing a typo in the samtools flagstat quality metric
  src/encoded/schemas/samtools_flagstats_quality_metric.json
Labels: Pending Travis Tests, ready to merge

#2242 ENCD-4015 adding an audit for read_count and test for it
  src/encoded/audit/file.py
  src/encoded/tests/test_audit_file.py
Labels: Pending Travis Tests

#2249 ENCD-3867 Display proper replicate_type string
  src/encoded/static/components/experiment.js
  src/encoded/static/components/filegallery.js
Labels: Pending QA

#2241 ENCD-4011 Fix wrong vars in buildout candidate config file
  buildout.cfg
  candidate.cfg
  ini-templates/production-template.ini
Labels: in progress

#2252 ENCD-3871-target-standard-status
  src/encoded/schemas/changelogs/target.md
  src/encoded/schemas/target.json
  src/encoded/static/components/testdata/lot_review.js
  src/encoded/static/components/testdata/target/HNRNPA1-human.js
  src/encoded/tests/data/inserts/target.json
  src/encoded/tests/test_upgrade_target.py
  src/encoded/upgrade/target.py
Labels: Pending QA

#2247 ENCD-3889 supersedes refepi
  src/encoded/loadxl.py
  src/encoded/schemas/changelogs/reference_epigenome.md
  src/encoded/schemas/reference_epigenome.json
  src/encoded/static/components/dataset.js
  src/encoded/static/components/experiment.js
  src/encoded/static/components/file.js
  src/encoded/static/components/typeutils.js
  src/encoded/types/dataset.py
  src/encoded/upgrade/dataset.py
Labels: Pending QA, Pending Travis Tests

#2257 ENCD-3364 fixed text and link button misalignment
  src/encoded/static/scss/encoded/modules/_visualize.scss
Labels: Pending QA

#2256 ENCD-3911 Added a break above document box
  src/encoded/static/components/item.js
Labels: Pending QA
