Repository ENCODE-DCC/encoded, pull requests merged in 2018-11, with the labels that each got.

#2460 ENCD-4239 Add biosample_type to query string on matrix click
  src/encoded/static/components/matrix.js
Labels: Pending QA

#2462 ENCD-4280 Remove table margin
  src/encoded/static/scss/encoded/modules/_facet.scss
  src/encoded/static/scss/encoded/modules/_tables.scss
Labels: Pending QA

#2463 ENCD-4256 Fix region search back button functionality
  src/encoded/static/components/region_search.js
Labels: Pending QA

#2468 ENCD-4282 Add PGP internal_tags badge
  src/encoded/static/img/tag-PGP.png
Labels: Pending QA

#2459 ENCD-4267 Remove files redirect from apache config
  etc/encoded-apache.conf
Labels: Pending QA

#2484 ENCD-4300 Remove checkfiles folder
  checkfiles/.gitignore
  checkfiles/README.rst
  checkfiles/checkfiles.py
  checkfiles/cloud-config.yml
  checkfiles/deploy.py
  checkfiles/requirements-deploy.txt
  checkfiles/requirements.txt
  checkfiles/script
Labels: Pending QA

#2481 ENCD-4252-disabled-download-restricted-files-admin
  src/encoded/static/components/objectutils.js
Labels: Ready to Merge

#2478 ENCD-4291-change-mod-type-category-gm-schema
  src/encoded/schemas/genetic_modification.json
Labels: Ready to Merge

#2486 ENCD-4295 fix target title in JSON
  src/encoded/types/target.py
Labels: Ready to Merge

#2475 ENCD-4271-fix-treatment-tem-id-regex
  src/encoded/schemas/mixins.json
Labels: Ready to Merge

#2461 ENCD-4244-audit-error-page
  src/encoded/viewconfigs/auditview.py
Labels: Pending QA

#2491 ENCD-4289 Update genetic modification tags metadata
  src/encoded/schemas/genetic_modification.json
  src/encoded/tests/test_schema_genetic_modification.py
Labels: Pending QA

#2467 ENCD-4223 Make internal_tags badges clickable to search pages
  src/encoded/static/components/__tests__/objectutils-test.js
  src/encoded/static/components/biosample.js
  src/encoded/static/components/dataset.js
  src/encoded/static/components/donor.js
  src/encoded/static/components/experiment.js
  src/encoded/static/components/objectutils.js
  src/encoded/tests/data/inserts/human_donor.json
Labels: Pending QA

#2465 ENCD-4281-fix-audit-text-message
  npm-shrinkwrap.json
  package.json
  src/encoded/static/components/auditmatrix.js
  src/encoded/static/components/matrix.js
Labels: Ready to Merge

#2492 ENCD-4033 Search page type-specific header (Req SNO-66)
  src/encoded/static/components/__tests__/server-render-test.js
  src/encoded/static/components/app.js
  src/encoded/static/components/auditmatrix.js
  src/encoded/static/components/matrix.js
  src/encoded/static/components/objectutils.js
  src/encoded/static/components/report.js
  src/encoded/static/components/search.js
  src/encoded/static/scss/encoded/modules/_facet.scss
  src/encoded/static/scss/encoded/modules/_matrix.scss
  src/encoded/static/scss/encoded/modules/_summary.scss
  src/encoded/static/scss/style.scss
  src/encoded/tests/features/audit.feature
  src/encoded/tests/features/matrix.feature
  src/encoded/tests/features/summary.feature
  src/encoded/tests/test_search.py
  src/encoded/viewconfigs/matrix.py
  src/encoded/viewconfigs/summary.py
Labels: Needs Snovault Update, Ready to Merge

#2493 ENCD-4279 Biosample preservation
  src/encoded/schemas/changelogs/biosample.md
  src/encoded/tests/test_types_biosample.py
  src/encoded/types/biosample.py
  src/encoded/types/experiment.py
Labels: Ready to Merge

#2490 ENCD-4245-skip-restricted-acl
  src/encoded/tests/test_status_trigger.py
  src/encoded/types/file.py
Labels: Pending QA

#2485 ENCD-4301 Refactor index UUID server
  buildout.cfg
  ini-templates/base-template.ini
  ini-templates/development-template.ini
  src/encoded/tests/features/test_trackhubs.py
  src/encoded/tests/test_indexing.py
Labels: Needs Snovault Update, Ready to Merge

#2515 ENCD-4297 Fix back button behavior and page jumping
  src/encoded/static/components/app.js
  src/encoded/static/components/search.js
  src/encoded/static/components/summary.js
  src/encoded/static/scss/encoded/modules/_facet.scss
  src/encoded/static/scss/encoded/modules/_summary.scss
Labels: Ready to Merge

#2511 ENCD-4326 Fix HTML entities for quotes
  src/encoded/static/components/errors.js
Labels: Ready to Merge

#2514 ENCD-4272-no-add-treatments
  src/encoded/schemas/changelogs/treatment.md
  src/encoded/schemas/treatment.json
  src/encoded/tests/data/inserts/treatment.json
  src/encoded/tests/test_types_treatment.py
  src/encoded/tests/test_upgrade_treatment.py
  src/encoded/types/__init__.py
  src/encoded/upgrade/treatment.py
Labels: Ready to Merge

#2516 ENCD-4319 improve BiosampleType
  src/encoded/audit/biosample_type.py
  src/encoded/schemas/biosample_type.json
  src/encoded/static/components/biosample_type.js
  src/encoded/tests/data/inserts/biosample_type.json
  src/encoded/tests/datafixtures.py
  src/encoded/tests/test_audit_biosample_type.py
  src/encoded/types/biosample_type.py
Labels: Ready to Merge
