Repository ENCODE-DCC/encoded, pull requests merged in 2018-06, with the labels that each got.

#2272 ENCD-3695-upgrade-to-boto3
  setup.py
  src/encoded/tests/test_file_download.py
  src/encoded/types/file.py
  versions.cfg
Labels: Needs Snovault Update

#2273 ENCD-4048-update-publication-data-raw-file-table
  src/encoded/static/components/filegallery.js
  src/encoded/static/scss/encoded/modules/_tables.scss
Labels: Conflict

#2280 ENCD-4058-expanding-matrix-creates-unaligned-headers-on-the-x-axis
  src/encoded/static/components/matrix.js
Labels: Pending QA, Pending Travis Tests

#2293 ENCD-4078-remove-unused-statuses
  src/encoded/schemas/file.json
  src/encoded/types/base.py
  src/encoded/types/user.py
Labels: Ready to Merge

#2295 ENCD-3776-move-to-standard-status
  src/encoded/schemas/changelogs/lab.md
  src/encoded/schemas/changelogs/organism.md
  src/encoded/schemas/changelogs/platform.md
  src/encoded/schemas/changelogs/source.md
  src/encoded/schemas/changelogs/treatment.md
  src/encoded/schemas/lab.json
  src/encoded/schemas/organism.json
  src/encoded/schemas/platform.json
  src/encoded/schemas/source.json
  src/encoded/schemas/treatment.json
  src/encoded/static/components/status.js
  src/encoded/static/components/testdata/lot_review.js
  src/encoded/static/components/testdata/source.js
  src/encoded/static/components/testdata/source/aviva.js
  src/encoded/tests/data/inserts/lab.json
  src/encoded/tests/data/inserts/organism.json
  src/encoded/tests/data/inserts/platform.json
  src/encoded/tests/data/inserts/source.json
  src/encoded/tests/data/inserts/treatment.json
  src/encoded/tests/datafixtures.py
  src/encoded/tests/test_upgrade_lab.py
  src/encoded/tests/test_upgrade_organism.py
  src/encoded/tests/test_upgrade_platform.py
  src/encoded/tests/test_upgrade_source.py
  src/encoded/tests/test_upgrade_treatment.py
  src/encoded/tests/test_views.py
  src/encoded/upgrade/lab.py
  src/encoded/upgrade/organism.py
  src/encoded/upgrade/platform.py
  src/encoded/upgrade/source.py
  src/encoded/upgrade/treatment.py
Labels: Ready to Merge

#2291 ENCD-4073 Revert accidental blocked dataset status expansion
  src/encoded/vis_defines.py
Labels: Ready to Merge

#2278 ENCD-3718-return-404-when-file-not-found
  src/encoded/tests/test_file_download.py
  src/encoded/types/file.py
Labels: Ready to Merge

#2294 ENCD-4040 vis index replicate conditional
  src/encoded/visualization.py
Labels: Ready to Merge

#2310 ENCD-4088 Remove extra code added in 3306
  src/encoded/static/components/filegallery.js
Labels: Pending QA

#2276 ENCD-4057-properly-format-data-on-biosample-page
  src/encoded/static/components/biosample.js
  src/encoded/static/components/donor.js
  src/encoded/static/libs/formatMeasurement.js
Labels: Ready to Merge

#2277 ENCD-4055-removed-some-styling-on-raw-data
  src/encoded/static/components/filegallery.js
Labels: Pending QA

#2296 ENCD-4020 Allowing specification of Sets as controls
  src/encoded/audit/experiment.py
  src/encoded/schemas/changelogs/experiment.md
  src/encoded/schemas/experiment.json
  src/encoded/tests/test_audit_experiment.py
  src/encoded/tests/test_schema_experiment.py
  src/encoded/types/dataset.py
Labels: Pending QA

#2306 ENCD-3728 Fix build error
  webpack.config.js
Labels: Pending Review

#2308 ENCD-4093 Fix initial region indexing failure
  src/encoded/region_indexer.py
Labels: Pending QA

#2279 REG-39 Regulome Release 1
  docs/region-search-viz-cache.rst
  src/encoded/batch_download.py
  src/encoded/commands/deploy.py
  src/encoded/commands/generate_scored_snps.py
  src/encoded/region_atlas.py
  src/encoded/region_indexer.py
  src/encoded/region_search.py
  src/encoded/schemas/annotation.json
  src/encoded/schemas/document.json
  src/encoded/schemas/file.json
  src/encoded/static/components/genome_browser.js
  src/encoded/static/components/region_search.js
  src/encoded/static/components/search.js
  src/encoded/tests/data/inserts/experiment.json
  src/encoded/tests/features/test_region_search.py
  src/encoded/tests/test_indexing.py
  src/encoded/vis_defines.py
  src/encoded/visualization.py
Labels: Do Not Merge, Merge to Regulome Master
