Repository ENCODE-DCC/encoded, pull requests merged in 2018-02, with the labels that each got.

#2105 ENCD-2567 New report page column selector modal
  src/encoded/static/components/report.js
  src/encoded/static/libs/bootstrap/modal.js
  src/encoded/static/scss/encoded/modules/_report.scss
  src/encoded/static/scss/style.scss
Labels: ready to merge

#2108 ENCD-3421 Properly link home chart to matrix
  src/encoded/static/components/home.js
  src/encoded/static/components/matrix.js
Labels: ready to merge

#2110 ENCD-3762 Add RegulomeDB to internal_tag and badge
  src/encoded/schemas/dataset.json
  src/encoded/static/img/tag-RegulomeDB.png
Labels: ready to merge

#2111 ENCD-3456 Stringify array and object items in a cell
  src/encoded/static/components/report.js
Labels: ready to merge

#2113 ENCD-3803 Allow fastq_sig to accept 3 in SRR headers
  src/encoded/schemas/changelogs/file.md
  src/encoded/schemas/file.json
Labels: ready to merge

#2117 ENCD-3827 Fix ES5 version in README
  README.md
Labels: ready to merge

#2118 ENCD-3816 Update selenium version to 3.8.1
  versions.cfg
Labels: ready to merge

#2119 ENCD-3798 Ontology Update Jan2018
  buildout.cfg
  src/encoded/commands/generate_ontology.py
  src/encoded/docs/updating_ontologies.md
Labels: ready to merge

#2120 ENCD-3820 Biosample: PMI property
  src/encoded/schemas/biosample.json
  src/encoded/schemas/changelogs/biosample.md
Labels: ready to merge

#2123 ENCD-3766 Add submitter comments to certain js pages
  src/encoded/schemas/file.json
  src/encoded/static/components/biosample.js
  src/encoded/static/components/donor.js
  src/encoded/static/components/experiment.js
  src/encoded/static/components/file.js
  src/encoded/static/components/filegallery.js
  src/encoded/static/components/genetic_modification.js
  src/encoded/static/components/pipeline.js
  src/encoded/types/genetic_modification.py
Labels: ready to merge

#2124 ENCD-3831 Add exp audit to flag standards violations
  src/encoded/audit/experiment.py
  src/encoded/audit/standards_data.py
  src/encoded/tests/test_audit_experiment.py
Labels: ready to merge

#2125 ENCD-3757 Adjust histone broad peak read depth audit
  src/encoded/audit/experiment.py
  src/encoded/audit/standards_data.py
Labels: Pending Data Review

#2134 ENCD-3853 Remove UCSC logos
  src/encoded/static/components/footer.js
  src/encoded/static/img/ucsc-logo-white-alt-2x.png
  src/encoded/static/img/ucsc-logo-white-alt.png
  src/encoded/static/img/ucsc-logo-white.png
  src/encoded/static/img/ucsc-logo.png
Labels: ready to merge

#2132 ENCD-3341 Add new output_types to file json
  src/encoded/schemas/changelogs/file.md
  src/encoded/schemas/file.json
Labels: ready to merge

#2133 ENCD-3835 Fix inconsistent platforms audit HiSeq2K 2.5K
  src/encoded/audit/experiment.py
Labels: ready to merge

#2122 ENCD-3819 Add biosample preservation method
  src/encoded/schemas/biosample.json
  src/encoded/schemas/changelogs/biosample.md
Labels: Pending Data Review

#2142 ENCD-3834 Add Alembic framework for Postgres migrations
  alembic.ini
  alembic/README
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/cfcf1fdff25c_add_rid_index_to_propsheets.py
  setup.py
  src/encoded/commands/alembic.py
Labels: ready to merge

#2151 ENCD-3879 Pin Alembic version
  versions.cfg
Labels: in progress

#2135 ENCD-3882 Update DOI preferred resolver url
  src/encoded/schemas/namespaces.json
  src/encoded/static/components/__tests__/dbxref-test.js
  src/encoded/static/components/dbxref.js
Labels: Trav-testing, ready to merge
