Repository ENCODE-DCC/encoded, pull requests merged in 2018-12, with the labels that each got.

#2526 ENCD-4315-cleanup-mutated-gene-khine
  src/encoded/audit/biosample.py
  src/encoded/schemas/biosample.json
  src/encoded/static/components/donor.js
  src/encoded/types/biosample.py
Labels: Ready to Merge

#2522 ENCD-4218 fix biodalliance visualize multiple datasets
  src/encoded/static/components/search.js
Labels: Ready to Merge

#2509 ENCD-4338 Allow repo to be specified on deploy
  cloud-config-cluster.yml
  cloud-config-no-es.yml
  cloud-config.yml
  src/encoded/commands/deploy.py
Labels: Pending QA

#2524 ENCD-4306-remove-improper-styling
  src/encoded/static/scss/encoded/modules/_forms.scss
Labels: Pending Travis Tests, Ready to Merge

#2536 ENCD-4358 add cell-free sample BiosampleType
  src/encoded/schemas/biosample_type.json
  src/encoded/tests/data/inserts/biosample_type.json
Labels: Ready to Merge

#2529 ENCD-4299 fix AntibodyLot.lot_reviews.organisms
  src/encoded/types/antibody_lot.py
Labels: Ready to Merge

#2520 ENCD-4334 add status facet
  src/encoded/types/experiment.py
Labels: Pending QA

#2535 ENCD-4323 Promote released objects
  src/encoded/static/components/antibody.js
  src/encoded/static/components/app.js
  src/encoded/static/components/biosample.js
  src/encoded/static/components/biosample_type.js
  src/encoded/static/components/dataset.js
  src/encoded/static/components/donor.js
  src/encoded/static/components/experiment.js
  src/encoded/static/components/gene.js
  src/encoded/static/components/genetic_modification.js
  src/encoded/static/components/navigation.js
  src/encoded/static/components/objectutils.js
  src/encoded/static/components/pipeline.js
  src/encoded/static/components/publication.js
  src/encoded/static/components/schema.js
  src/encoded/static/components/software.js
  src/encoded/static/components/target.js
  src/encoded/static/components/user.js
  src/encoded/tests/features/matrix.feature
  src/encoded/tests/features/search.feature
  src/encoded/tests/features/summary.feature
  src/encoded/tests/features/title.feature
Labels: Ready to Merge

#2503 ENCD-4333 Add release candidate options to deploy
  cloud-config-cluster.yml
  cloud-config-no-es.yml
  cloud-config.yml
  rc.cfg
  src/encoded/commands/deploy.py
Labels: Pending Travis Tests, Ready to Merge

#2523 ENCD-3665 add file format dependency
  src/encoded/schemas/file.json
  src/encoded/tests/test_audit_item.py
  src/encoded/tests/test_schema_file.py
Labels: Ready to Merge

#2528 ENCD-4312 genetic modification audit
  src/encoded/audit/genetic_modification.py
  src/encoded/schemas/changelogs/genetic_modification.md
  src/encoded/schemas/genetic_modification.json
  src/encoded/tests/test_schema_genetic_modification.py
Labels: Ready to Merge

#2540 ENCD-4335 Remove npm shrinkwrap again
  buildout.cfg
  npm-shrinkwrap.json
Labels: Pending QA

#2542 ENCD-4367 Update simple for queue module
  ini-templates/base-template.ini
  ini-templates/development-template.ini
  src/encoded/tests/test_indexing.py
Labels: Ready to Merge
