Repository ENCODE-DCC/encoded, pull requests merged in 2018-07, with the labels that each got.

#2309 ENCD-4051-Change schemas to set minimum int values
  src/encoded/schemas/analysis_step.json
  src/encoded/schemas/analysis_step_version.json
  src/encoded/schemas/antibody_characterization.json
  src/encoded/schemas/biosample.json
  src/encoded/schemas/changelogs/analysis_step.md
  src/encoded/schemas/changelogs/analysis_step_version.md
  src/encoded/schemas/changelogs/antibody_characterization.md
  src/encoded/schemas/changelogs/biosample.md
  src/encoded/schemas/changelogs/chipseq_filter_quality_metric.md
  src/encoded/schemas/changelogs/complexity_xcorr_quality_metric.md
  src/encoded/schemas/changelogs/file.md
  src/encoded/schemas/changelogs/generic_quality_metric.md
  src/encoded/schemas/changelogs/genetic_modification_characterization.md
  src/encoded/schemas/changelogs/histone_chipseq_quality_metric.md
  src/encoded/schemas/changelogs/idr_quality_metric.md
  src/encoded/schemas/changelogs/idr_summary_quality_metric.md
  src/encoded/schemas/changelogs/mad_quality_metric.md
  src/encoded/schemas/changelogs/mixins.md
  src/encoded/schemas/changelogs/pipeline.md
  src/encoded/schemas/changelogs/quality_metric.md
  src/encoded/schemas/changelogs/replicate.md
  src/encoded/schemas/chipseq_filter_quality_metric.json
  src/encoded/schemas/complexity_xcorr_quality_metric.json
  src/encoded/schemas/file.json
  src/encoded/schemas/generic_quality_metric.json
  src/encoded/schemas/genetic_modification_characterization.json
  src/encoded/schemas/histone_chipseq_quality_metric.json
  src/encoded/schemas/idr_quality_metric.json
  src/encoded/schemas/idr_summary_quality_metric.json
  src/encoded/schemas/mad_quality_metric.json
  src/encoded/schemas/mixins.json
  src/encoded/schemas/pipeline.json
  src/encoded/schemas/quality_metric.json
  src/encoded/schemas/replicate.json
Labels: Ready to Merge

#2312 ENCD-4087-fixed-flybase-search
  src/encoded/static/components/__tests__/dbxref-test.js
  src/encoded/static/components/dbxref.js
Labels: Ready to Merge

#2322 ENCD-3563 adjust single cell replication audit
  src/encoded/audit/experiment.py
  src/encoded/tests/test_audit_experiment.py
Labels: Ready to Merge

#2332 ENCD-3903 add documentation for schema page
  src/encoded/static/components/schema.js
  src/encoded/static/scss/encoded/modules/_blocks.scss
Labels: Ready to Merge

#2327 ENCD-4102 changed audit from WARNING to ERROR
  src/encoded/audit/genetic_modification.py
Labels: Pending Travis Tests, Ready to Merge

#2313 ENCD-4074-toolip-overlay
  src/encoded/static/scss/encoded/modules/_facet.scss
Labels: Pending Travis Tests, Ready to Merge

#2315 ENCD-4089-Deactivated-rep-num-in-annot-table
  src/encoded/static/components/dataset.js
Labels: Pending Review, Pending Travis Tests, Ready to Merge

#2324 ENCD-4108 audit matched
  src/encoded/audit/experiment.py
  src/encoded/tests/test_audit_experiment.py
Labels: Pending QA

#2326 ENCD-4017 Fulfill ECP requests for home page additions.
  .gitignore
  src/encoded/static/components/app.js
  src/encoded/static/components/home.js
  src/encoded/static/libs/bootstrap/tooltip.js
  src/encoded/static/scss/encoded/modules/_home.scss
  src/encoded/static/scss/encoded/modules/_tooltip.scss
Labels: Pending QA

#2339 [2nd] ENCD-4108 Missing return after yield
  src/encoded/audit/experiment.py
Labels: Pending Travis Tests

#2346 ENCD-4143-add-assert-call-count
  src/encoded/tests/test_status_trigger.py
Labels: Pending QA
