Repository ENCODE-DCC/encoded, pull requests merged in 2018-08, with the labels that each got.

#2348 ENCD-4134 add RIN number property to Library
  src/encoded/schemas/changelogs/library.md
  src/encoded/schemas/library.json
  src/encoded/tests/data/inserts/library.json
Labels: Pending QA, Pending Travis Tests

#2330 ENCD-4107: added experiment_class to experiment schema
  src/encoded/schemas/changelogs/experiment.md
  src/encoded/schemas/experiment.json
  src/encoded/tests/data/inserts/experiment.json
  src/encoded/tests/datafixtures.py
  src/encoded/tests/test_audit_experiment.py
  src/encoded/tests/test_audit_file.py
  src/encoded/tests/test_audit_reference_epigenome.py
  src/encoded/tests/test_audit_replicate.py
  src/encoded/tests/test_permissions.py
  src/encoded/tests/test_schema_experiment.py
  src/encoded/tests/test_types_experiment.py
  src/encoded/tests/test_types_series.py
  src/encoded/upgrade/dataset.py
Labels: Pending Travis Tests, in progress

#2354 ENCD-4152 Make organism.scientific_name required
  src/encoded/schemas/changelogs/organism.md
  src/encoded/schemas/organism.json
  src/encoded/tests/data/inserts/organism.json
  src/encoded/upgrade/organism.py
Labels: Pending Travis Tests

#2344 ENCD-4141 Add alias namespaces
  src/encoded/schemas/mixins.json
  src/encoded/tests/data/inserts/biosample.json
  src/encoded/tests/data/inserts/document.json
Labels: Pending Travis Tests

#2355 ENCD-4154 Remove unused search type arg
  src/encoded/search.py
Labels: Pending QA

#2343 ENCD-4123 audit chip
  src/encoded/audit/experiment.py
  src/encoded/tests/test_audit_experiment.py
Labels: Pending QA

#2307 ENCD-3997 Create Gene object
  src/encoded/loadxl.py
  src/encoded/schemas/changelogs/gene.md
  src/encoded/schemas/gene.json
  src/encoded/search.py
  src/encoded/static/components/dbxref.js
  src/encoded/static/components/gene.js
  src/encoded/static/components/index.js
  src/encoded/static/components/search.js
  src/encoded/tests/data/inserts/gene.json
  src/encoded/types/gene.py
Labels: Pending QA

#2365 ENCD-4166 RIN internal action audit
  src/encoded/audit/experiment.py
  src/encoded/tests/test_audit_experiment.py
Labels: Pending QA

#2335 ENCD-4038 Adding matrix bdd tests
  src/encoded/tests/features/matrix.feature
  src/encoded/tests/features/test_matrix.py
Labels: Pending Travis Tests, Ready to Merge

#2366 ENCD-4159 adjusting GM characterization audit
  src/encoded/audit/experiment.py
  src/encoded/audit/genetic_modification.py
  src/encoded/tests/datafixtures.py
  src/encoded/tests/test_audit_experiment.py
  src/encoded/tests/test_audit_genetic_modification.py
Labels: Ready to Merge

#2371 ENCD-4160 Add Casey Jason Zack to user inserts
  src/encoded/tests/data/inserts/user.json
Labels: Pending QA

#2375 ENCD-4135-integrity-num
  src/encoded/static/components/experiment.js
Labels: Pending QA
