Repository ENCODE-DCC/encoded, pull requests merged in 2019-06, with the labels that each got.

#2763 ENCD-4613 Change cRE to cCRE
  src/encoded/schemas/analysis_step.json
  src/encoded/schemas/annotation.json
  src/encoded/schemas/changelogs/analysis_step.md
  src/encoded/schemas/changelogs/annotation.md
  src/encoded/schemas/changelogs/file.md
  src/encoded/schemas/file.json
  src/encoded/static/components/home.js
  src/encoded/tests/data/inserts/annotation.json
  src/encoded/tests/test_upgrade_analysis_step.py
  src/encoded/tests/test_upgrade_dataset.py
  src/encoded/tests/test_upgrade_file.py
  src/encoded/upgrade/analysis_step.py
  src/encoded/upgrade/dataset.py
  src/encoded/upgrade/file.py
  src/encoded/vis_defines.py
Labels: Has Dependency

#2797 ENCD-4062 Fix read name details dependency
  src/encoded/schemas/file.json
  src/encoded/tests/test_schema_file.py
Labels: Ready to Merge

#2812 ENCD-4662 Experiment series
  src/encoded/loadxl.py
  src/encoded/schemas/changelogs/experiment_series.md
  src/encoded/schemas/experiment_series.json
  src/encoded/static/components/__tests__/objectutils-test.js
  src/encoded/static/components/biosample.js
  src/encoded/static/components/dataset.js
  src/encoded/static/components/donor.js
  src/encoded/static/components/experiment.js
  src/encoded/static/components/experiment_series.js
  src/encoded/static/components/index.js
  src/encoded/static/components/objectutils.js
  src/encoded/static/components/sorttable.js
  src/encoded/static/components/status.js
  src/encoded/static/scss/encoded/modules/_search.scss
  src/encoded/static/scss/encoded/modules/_tables.scss
  src/encoded/tests/data/inserts/award.json
  src/encoded/tests/data/inserts/experiment_series.json
  src/encoded/types/dataset.py
Labels: Do Not Merge, Has Dependency

#2822 ENCD-4698-update-snovault-1.0.32
  buildout.cfg
Labels: Has Dependency
