Repository ENCODE-DCC/encoded, pull requests merged in 2019-03, with the labels that each got.

#2615 ENCD-4476-add-spaces-schema
  src/encoded/schemas/changelogs/annotation.md
  src/encoded/schemas/changelogs/antibody_characterization.md
  src/encoded/schemas/changelogs/biosample.md
  src/encoded/schemas/changelogs/experiment.md
Labels: Ready to Merge

#2620 ENCD-4348 Restrict ontologies for in vitro diff cells
  src/encoded/schemas/biosample_type.json
  src/encoded/schemas/changelogs/biosample_type.md
Labels: Pending QA

#2625 ENCD-4484 Allow deployment set ssh id file
  src/encoded/commands/deploy.py
Labels: Pending QA

#2627 ENCD-4217 Rendering error series objects
  src/encoded/static/components/dataset.js
  src/encoded/tests/data/inserts/experiment.json
  src/encoded/tests/data/inserts/organism_development_series.json
  src/encoded/tests/data/inserts/replicate.json
  src/encoded/tests/test_batch_download.py
Labels: Pending QA

#2616 ENCD-4401-remove-approvalrequired
  src/encoded/schemas/experiment.json
  src/encoded/schemas/replicate.json
  src/encoded/static/components/schema.js
Labels: Ready to Merge

#2628 ENCD-4467 Numerical facets sorted by value not frequency
  src/encoded/schemas/aggregate_series.json
  src/encoded/schemas/experiment.json
  src/encoded/schemas/matched_set.json
  src/encoded/schemas/organism_development_series.json
  src/encoded/schemas/reference_epigenome.json
  src/encoded/schemas/replication_timing_series.json
  src/encoded/schemas/treatment_concentration_series.json
  src/encoded/schemas/treatment_time_series.json
  src/encoded/static/components/search.js
Labels: Pending QA

#2629 ENCD-4485 bug report camel case
  src/encoded/batch_download.py
  src/encoded/tests/test_batch_download.py
Labels: Pending QA

#2631 ENCD-4457 organoid age
  src/encoded/audit/biosample.py
  src/encoded/schemas/biosample.json
  src/encoded/schemas/changelogs/biosample.md
  src/encoded/static/components/biosample.js
  src/encoded/tests/data/inserts/biosample.json
  src/encoded/tests/data/inserts/biosample_type.json
  src/encoded/tests/test_audit_biosample.py
  src/encoded/tests/test_schema_biosample.py
Labels: Ready to Merge

#2633 ENCD-4305 Turn Superseded by into links on exp file pages
  src/encoded/static/components/__tests__/experiment-test.js
  src/encoded/static/components/experiment.js
  src/encoded/static/components/objectutils.js
  src/encoded/static/components/typeutils.js
  src/encoded/static/scss/encoded/_base.scss
  src/encoded/tests/data/inserts/file.json
Labels: in progress

#2623 ENCD-4473-add-MPRA-assay
  src/encoded/audit/experiment.py
  src/encoded/schemas/award.json
  src/encoded/schemas/mixins.json
  src/encoded/schemas/pipeline.json
  src/encoded/schemas/software.json
  src/encoded/tests/data/inserts/experiment.json
  src/encoded/tests/test_batch_download.py
  src/encoded/types/assay_data.py
Labels: Ready to Merge

#2622 ENCD-4132 analysis object
  src/encoded/audit/analysis.py
  src/encoded/audit/file.py
  src/encoded/loadxl.py
  src/encoded/schema_formats.py
  src/encoded/schemas/analysis.json
  src/encoded/schemas/analysis_step_run.json
  src/encoded/schemas/changelogs/analysis.md
  src/encoded/static/components/analysis.js
  src/encoded/static/components/index.js
  src/encoded/tests/data/inserts/analysis.json
  src/encoded/tests/data/inserts/analysis_step_run.json
  src/encoded/tests/data/inserts/file.json
  src/encoded/tests/test_audit_analysis.py
  src/encoded/tests/test_audit_file.py
  src/encoded/types/analysis.py
  src/encoded/types/dataset.py
  src/encoded/types/file.py
  src/encoded/types/pipeline.py
Labels: Pending Code Review

#2617 ENCD-4474 model restriction map
  src/encoded/schemas/changelogs/file.md
  src/encoded/schemas/file.json
  src/encoded/static/components/file.js
  src/encoded/tests/data/inserts/file.json
  src/encoded/tests/test_schema_file.py
Labels: Pending QA

#2607 ENCD-3877-4449-annotation download btn
  src/encoded/batch_download.py
  src/encoded/helpers/helper.py
  src/encoded/types/dataset.py
Labels: Pending Code Review

#2539 ENCD-4353-Refactor-out-matrix-and-result
  src/encoded/viewconfigs/matrix.py
Labels: Pending QA

#2626 ENCD-4483 Cleanup deploy output
  src/encoded/commands/deploy.py
Labels: in progress

#2624 ENCD-4482 adding lane to characterizations review
  src/encoded/schemas/biosample_characterization.json
  src/encoded/schemas/genetic_modification_characterization.json
  src/encoded/schemas/mixins.json
  src/encoded/tests/data/inserts/biosample_characterization.json
  src/encoded/tests/test_permissions.py
  src/encoded/tests/test_schema_genetic_modification_characterization.py
Labels: Ready to Merge

#2614 ENCD-3901 Support multiple carts per user
  src/encoded/cart_view.py
  src/encoded/schemas/cart.json
  src/encoded/schemas/changelogs/cart.md
  src/encoded/static/components/__tests__/cart-test.js
  src/encoded/static/components/__tests__/experiment-test.js
  src/encoded/static/components/app.js
  src/encoded/static/components/cart/actions.js
  src/encoded/static/components/cart/add_multiple.js
  src/encoded/static/components/cart/batch_download.js
  src/encoded/static/components/cart/cart.js
  src/encoded/static/components/cart/clear.js
  src/encoded/static/components/cart/database.js
  src/encoded/static/components/cart/in_progress.js
  src/encoded/static/components/cart/index.js
  src/encoded/static/components/cart/manager.js
  src/encoded/static/components/cart/merge_shared.js
  src/encoded/static/components/cart/save.js
  src/encoded/static/components/cart/set_current.js
  src/encoded/static/components/cart/settings.js
  src/encoded/static/components/cart/share.js
  src/encoded/static/components/cart/status.js
  src/encoded/static/components/cart/switch.js
  src/encoded/static/components/cart/toggle.js
  src/encoded/static/components/index.js
  src/encoded/static/components/search.js
  src/encoded/static/components/sorttable.js
  src/encoded/static/components/status.js
  src/encoded/static/components/user.js
  src/encoded/static/libs/bootstrap/modal.js
  src/encoded/static/scss/encoded/modules/_cart.scss
  src/encoded/static/scss/encoded/modules/_forms.scss
  src/encoded/static/scss/encoded/modules/_navbar.scss
  src/encoded/static/scss/encoded/modules/_tables.scss
  src/encoded/static/scss/fontawesome/_icons.scss
  src/encoded/tests/data/inserts/cart.json
  src/encoded/tests/test_types_carts.py
  src/encoded/types/cart.py
Labels: Pending QA

#2634 ENCD-4464 add GM category enums
  src/encoded/schemas/changelogs/genetic_modification.md
  src/encoded/schemas/genetic_modification.json
  src/encoded/tests/data/inserts/genetic_modification.json
  src/encoded/tests/test_schema_genetic_modification.py
Labels: Pending Code Review

#2660 ENCD-3422-datasets-table-publication
  src/encoded/static/components/__tests__/publication-test.js
  src/encoded/static/components/fetched.js
  src/encoded/static/components/publication.js
Labels: Pending Code Review

#2646 ENCD-4469 Add stimulation to treatment type
  src/encoded/schemas/changelogs/treatment.md
  src/encoded/schemas/mixins.json
Labels: Pending Code Review

#2653 ENCD-4521-add-insert-user-meenakshi
  src/encoded/tests/data/inserts/user.json
Labels: Pending QA

#2661 ENCD-4507 Handle long cart operations
  src/encoded/static/components/app.js
  src/encoded/static/components/cart/actions.js
  src/encoded/static/components/cart/cart.js
  src/encoded/static/components/cart/database.js
  src/encoded/static/components/cart/manager.js
  src/encoded/static/components/cart/status.js
  src/encoded/static/components/cart/switch.js
  src/encoded/static/libs/svg-icons.js
  src/encoded/static/scss/encoded/modules/_cart.scss
Labels: Pending QA

#2665 ENCD-4414 Allow users to add exp to carts from series
  src/encoded/static/components/cart/add_multiple.js
  src/encoded/static/components/cart/index.js
  src/encoded/static/components/cart/search_controls.js
  src/encoded/static/components/cart/toggle.js
  src/encoded/static/components/dataset.js
  src/encoded/static/scss/encoded/modules/_cart.scss
  src/encoded/static/scss/encoded/modules/_facet.scss
Labels: Pending QA

#2654 ENCD-4489 add imputation annotation_type
  src/encoded/schemas/annotation.json
  src/encoded/schemas/changelogs/annotation.md
  src/encoded/tests/data/inserts/annotation.json
  src/encoded/tests/datafixtures.py
  src/encoded/tests/test_upgrade_dataset.py
  src/encoded/upgrade/dataset.py
Labels: Pending QA

#2666 ENCD-4347-4384-3952 ontology update
  buildout.cfg
  src/encoded/commands/generate_ontology.py
  src/encoded/docs/updating_ontologies.md
  src/encoded/schemas/award.json
  src/encoded/schemas/changelogs/experiment.md
  src/encoded/schemas/experiment.json
  src/encoded/schemas/mixins.json
  src/encoded/schemas/pipeline.json
  src/encoded/schemas/software.json
  src/encoded/tests/data/inserts/experiment.json
  src/encoded/tests/data/inserts/pipeline.json
  src/encoded/tests/test_batch_download.py
  src/encoded/tests/test_upgrade_dataset.py
  src/encoded/types/assay_data.py
  src/encoded/upgrade/dataset.py
Labels: Pending QA

#2667 SNO-83 Rotate img attachment for EXIF
  buildout.cfg
Labels: Ready to Merge

#2671 ENCD-4517 Add UI for GM introduced elements
  src/encoded/static/components/genetic_modification.js
Labels: Ready to Merge

#2685 ENCD-3919-index-vis-blobs-on-deploy
  src/encoded/vis_indexer.py
  src/encoded/visualization.py
Labels: Ready to Merge
