Repository ENCODE-DCC/encoded, pull requests merged in 2019-02, with the labels that each got.

#2572 ENCD-4402 Add Jennifer Z to submitters
  src/encoded/tests/data/inserts/user.json
Labels: Ready to Merge

#2583 ENCD-4416 Revise audit_inherit list of AntibodyLots
  src/encoded/types/antibody_lot.py
Labels: Pending Code Review

#2582 ENCD-4405 Add enrichment to analysis step types enum
  src/encoded/schemas/analysis_step.json
Labels: Pending Code Review

#2584 ENCD-4227-add-PLAC-seq-to-assays
  src/encoded/audit/experiment.py
  src/encoded/schemas/award.json
  src/encoded/schemas/mixins.json
  src/encoded/schemas/pipeline.json
  src/encoded/schemas/software.json
  src/encoded/tests/data/inserts/experiment.json
  src/encoded/tests/test_audit_experiment.py
  src/encoded/tests/test_batch_download.py
  src/encoded/types/assay_data.py
Labels: Ready to Merge

#2570 ENCD-4406 exclude fly RNAi from reagents audit
  src/encoded/audit/genetic_modification.py
  src/encoded/schemas/genetic_modification.json
  src/encoded/tests/test_audit_genetic_modification.py
Labels: Ready to Merge

#2588 ENCD-4435 Add ENCv5 ccre internal_tags to datasets
  src/encoded/schemas/annotation.json
  src/encoded/schemas/changelogs/annotation.md
  src/encoded/schemas/changelogs/dataset.md
  src/encoded/schemas/changelogs/experiment.md
  src/encoded/schemas/changelogs/matched_set.md
  src/encoded/schemas/changelogs/organism_development_series.md
  src/encoded/schemas/changelogs/project.md
  src/encoded/schemas/changelogs/publication_data.md
  src/encoded/schemas/changelogs/reference.md
  src/encoded/schemas/changelogs/reference_epigenome.md
  src/encoded/schemas/changelogs/replication_timing_series.md
  src/encoded/schemas/changelogs/treatment_concentration_series.md
  src/encoded/schemas/changelogs/treatment_time_series.md
  src/encoded/schemas/changelogs/ucsc_browser_composite.md
  src/encoded/schemas/dataset.json
  src/encoded/schemas/experiment.json
  src/encoded/schemas/matched_set.json
  src/encoded/schemas/organism_development_series.json
  src/encoded/schemas/project.json
  src/encoded/schemas/publication_data.json
  src/encoded/schemas/reference.json
  src/encoded/schemas/reference_epigenome.json
  src/encoded/schemas/replication_timing_series.json
  src/encoded/schemas/treatment_concentration_series.json
  src/encoded/schemas/treatment_time_series.json
  src/encoded/schemas/ucsc_browser_composite.json
  src/encoded/static/img/tag-ENCYCLOPEDIAv5.png
  src/encoded/static/img/tag-ccre_inputv1.png
  src/encoded/static/img/tag-ccre_inputv2.png
  src/encoded/tests/test_upgrade_dataset.py
  src/encoded/upgrade/dataset.py
Labels: Pending Travis Tests, Ready to Merge

#2589 ENCD-4419 use biosample ontology for audit
  src/encoded/audit/experiment.py
  src/encoded/tests/test_audit_experiment.py
Labels: Ready to Merge

#2537 ENCD-4014 library restriction enzyme audit
  src/encoded/audit/experiment.py
  src/encoded/tests/test_audit_experiment.py
Labels: Pending QA

#2585 ENCD-4420 Remove biosample type name id props
  src/encoded/schemas/annotation.json
  src/encoded/schemas/antibody_characterization.json
  src/encoded/schemas/biosample.json
  src/encoded/schemas/changelogs/annotation.md
  src/encoded/schemas/changelogs/antibody_characterization.md
  src/encoded/schemas/changelogs/biosample.md
  src/encoded/schemas/changelogs/experiment.md
  src/encoded/schemas/experiment.json
  src/encoded/schemas/mixins.json
  src/encoded/static/components/__tests__/cart-test.js
  src/encoded/static/components/antibody.js
  src/encoded/static/components/auditmatrix.js
  src/encoded/static/components/matrix.js
  src/encoded/static/components/testdata/biosample/k562-1.js
  src/encoded/static/components/testdata/biosample/uberon-2371.js
  src/encoded/static/components/testdata/characterization/antibody-367a6fdd0cef.js
  src/encoded/static/components/testdata/experiment.js
  src/encoded/tests/data/inserts/annotation.json
  src/encoded/tests/data/inserts/antibody_characterization.json
  src/encoded/tests/data/inserts/biosample.json
  src/encoded/tests/data/inserts/experiment.json
  src/encoded/tests/datafixtures.py
  src/encoded/tests/test_audit_antibody_characterization.py
  src/encoded/tests/test_audit_antibody_lot.py
  src/encoded/tests/test_audit_biosample.py
  src/encoded/tests/test_audit_biosample_type.py
  src/encoded/tests/test_audit_experiment.py
  src/encoded/tests/test_audit_file.py
  src/encoded/tests/test_audit_reference_epigenome.py
  src/encoded/tests/test_audit_replicate.py
  src/encoded/tests/test_batch_download.py
  src/encoded/tests/test_ontology_slims.py
  src/encoded/tests/test_permissions.py
  src/encoded/tests/test_schema_antibody_characterization.py
  src/encoded/tests/test_schema_biosample.py
  src/encoded/tests/test_schema_experiment.py
  src/encoded/tests/test_types_antibody_lot.py
  src/encoded/tests/test_types_biosample.py
  src/encoded/tests/test_types_experiment.py
  src/encoded/tests/test_types_series.py
  src/encoded/tests/test_upgrade_biosample.py
  src/encoded/tests/test_upgrade_characterization.py
  src/encoded/tests/test_upgrade_dataset.py
  src/encoded/types/biosample.py
  src/encoded/types/experiment.py
  src/encoded/types/shared_calculated_properties.py
  src/encoded/upgrade/biosample.py
  src/encoded/upgrade/characterization.py
  src/encoded/upgrade/dataset.py
Labels: Ready to Merge

#2587 ENCD-4444 Highlight selected facet terms numbers
  src/encoded/static/components/search.js
Labels: Ready to Merge

#2571 ENCD-4431 change report file download name
  src/encoded/batch_download.py
  src/encoded/tests/test_batch_download.py
Labels: Ready to Merge

#2567 ENCD-4251 Combine reorganize technical replicates
  src/encoded/audit/experiment.py
  src/encoded/audit/file.py
  src/encoded/tests/test_file.py
  src/encoded/types/__init__.py
  src/encoded/types/dataset.py
  src/encoded/types/experiment.py
  src/encoded/types/file.py
  src/encoded/types/shared_calculated_properties.py
Labels: Pending QA

#2590 ENCD-4298 Ontology update colon and PLAC-seq
  buildout.cfg
  src/encoded/commands/generate_ontology.py
  src/encoded/docs/updating_ontologies.md
Labels: in progress

#2580 ENCD-4427-file-bucket-audit
  buildout.cfg
  candidate.cfg
  ini-templates/base-template.ini
  ini-templates/production-template.ini
  src/encoded/audit/file.py
  src/encoded/tests/datafixtures.py
  src/encoded/tests/test_audit_file.py
  src/encoded/tests/test_types_file.py
  src/encoded/types/file.py
Labels: Ready to Merge

#2594 ENCD-4453 adding idx file_format
  src/encoded/schemas/changelogs/file.md
  src/encoded/schemas/file.json
  src/encoded/tests/data/inserts/file.json
Labels: Pending QA

#2599 ENCD-4455-bucket-notify
  src/encoded/types/file.py
Labels: Pending Code Review

#2597 ENCD-4445 Handle log-in changes for related files in file tables.
  src/encoded/static/components/filegallery.js
Labels: Ready to Merge

#2598 ENCD-4425 Update audits exp and genetic mod targets
  src/encoded/audit/experiment.py
  src/encoded/audit/genetic_modification.py
  src/encoded/tests/test_audit_experiment.py
  src/encoded/tests/test_audit_genetic_modification.py
Labels: Pending QA

#2591 ENCD-4240 Allow review characterizations
  src/encoded/schemas/biosample_characterization.json
  src/encoded/schemas/changelogs/biosample_characterization.md
  src/encoded/schemas/changelogs/genetic_modification_characterization.md
  src/encoded/schemas/genetic_modification_characterization.json
  src/encoded/schemas/mixins.json
  src/encoded/tests/test_permissions.py
  src/encoded/tests/test_schema_genetic_modification_characterization.py
  src/encoded/types/characterization.py
Labels: Do Not Merge, Needs Snovault Update, Ready to Merge, in progress

#2602 ENCD-4461 Revert libraries for exp type matrix
  src/encoded/types/experiment.py
Labels: Pending QA, Pending Travis Tests

#2606 ENCD-4462 fixing the AB characterization view bug
  src/encoded/tests/test_permissions.py
  src/encoded/types/characterization.py
Labels: Ready to Merge

#2549 SNO-73-ENCD-4456 Add uuid queue module
  .travis.yml
  buildout.cfg
  candidate.cfg
  cloud-config-no-es.yml
  cloud-config.yml
  ini-templates/base-template.ini
  ini-templates/development-template.ini
  src/encoded/commands/deploy.py
  src/encoded/region_indexer.py
  src/encoded/tests/test_indexing.py
  src/encoded/vis_indexer.py
  test.cfg
Labels: Needs Snovault Update
