Repository ENCODE-DCC/encoded, pull requests merged in 2019-01, with the labels that each got.

#2550 ENCD-4377 add Ubiquitination to target mod enum
  src/encoded/schemas/changelogs/target.md
  src/encoded/schemas/target.json
Labels: Pending Travis Tests, Ready to Merge

#2543 ENCD-4369 Install redis server
  cloud-config-cluster.yml
  cloud-config-no-es.yml
  cloud-config.yml
  src/encoded/commands/deploy.py
Labels: Ready to Merge

#2556 ENCD-4393-add-gene-alignments
  src/encoded/schemas/analysis_step.json
  src/encoded/schemas/changelogs/analysis_step.md
  src/encoded/schemas/changelogs/file.md
  src/encoded/schemas/file.json
Labels: Pending Code Review

#2559 ENCD-4355 add introduced gene link
  src/encoded/schemas/changelogs/genetic_modification.md
  src/encoded/schemas/genetic_modification.json
  src/encoded/static/components/genetic_modification.js
  src/encoded/tests/data/inserts/genetic_modification.json
Labels: in progress

#2551 ENCD-4388 excluding not relevant experiments form RE audits
  src/encoded/audit/reference_epigenome.py
  src/encoded/tests/test_audit_reference_epigenome.py
Labels: Pending Travis Tests, Ready to Merge, in progress

#2555 ENCD-4396 Citation note
  src/encoded/static/components/app.js
  src/encoded/static/components/footer.js
  src/encoded/static/components/home.js
  src/encoded/static/libs/bootstrap/modal.js
  src/encoded/static/scss/encoded/_base.scss
  src/encoded/static/scss/encoded/_layout.scss
  src/encoded/static/scss/encoded/_state.scss
  src/encoded/static/scss/encoded/modules/_home.scss
Labels: Ready to Merge

#2554 ENCD-4325 Juicebox browser
  src/encoded/static/components/filegallery.js
  src/encoded/static/components/globals.js
  src/encoded/static/components/search.js
  src/encoded/static/components/vis_defines.js
  src/encoded/static/libs/bootstrap/panel.js
  src/encoded/static/scss/encoded/modules/_panels.scss
  src/encoded/tests/data/inserts/file.json
  src/encoded/tests/features/test_trackhubs.py
  src/encoded/types/shared_calculated_properties.py
  src/encoded/vis_defines.py
Labels: Pending Travis Tests, Ready to Merge

#2552 ENCD-4359 Fix recursive is_part_of audit function
  src/encoded/audit/biosample.py
  src/encoded/tests/test_audit_biosample.py
Labels: Pending Travis Tests, Ready to Merge

#2553 ENCD-3971 Update node npm to version 10
  .travis.yml
  README.md
  buildout.cfg
  cloud-config-cluster.yml
  cloud-config-no-es.yml
  cloud-config.yml
  docs/npm-packages.md
  package-lock.json
  package.json
Labels: Ready to Merge

#2564 [2nd] ENCD-4360 fix schemas and add BiosampleType to search
  src/encoded/schemas/annotation.json
  src/encoded/schemas/biosample.json
  src/encoded/viewconfigs/views.py
Labels: Ready to Merge

#2566 ENCD-4423 Update dalliance to version 1.0
  package-lock.json
  package.json
Labels: Ready to Merge

#2565 [2nd] ENCD-4325 Juicebox browser mods for annos
  src/encoded/static/components/filegallery.js
  src/encoded/static/components/vis_defines.js
  src/encoded/vis_defines.py
Labels: Pending QA
